### PR TITLE
Docu: Make Cluster Controller defaults more clear

### PR DESCRIPTION
**Pull request by scholzj**
### Type of change

- Bugfix
- ~~Enhancement / new feature~~
- ~~Refactoring~~

### Description

This clarifies the documentation regarding the Cluster Controller environment variables and their default values.

### Checklist

- [x] Update documentation

### CODE REVIEW

**Comment by scholzj** [comment]
@tombentley Your changes look good. Can I merge it now? Or are you planning some more changes:

**Comment by tombentley** [comment]
I'm sympathetic to that point of view @ppatierno, but the way it was before
the optionality and default value were lost in the text. I don't like
having to scan through a load of text to find whether I have to set it
override a value. We could use a table I suppose, but that can end up
wasting space.

**Comment by tombentley** [comment]
@scholzj I'm finished with it, so if @ppatierno is ok with it you can
merge.

**Comment by ppatierno** [comment]
@tombentley yes I think that using a table could be a great idea. This is the Kafka documentation way as well.

**Pull request merged**
