### PR TITLE
Added OpenShift dashboard route for Grafana

### PR DESCRIPTION
**Pull request by ppatierno**
### Type of change

_Select the type of your PR_

- Enhancement / new feature

### Description

This PR just adds a Route for the Grafana dashboard when the cluster is deployed on OpenShift.

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging

### CODE REVIEW

**Comment by ppatierno** [comment]
@tombentley @scholzj I had a doubt on how describing that a route is available for OpenShift. Exposing when running on minishift/minikube is in a NOTE but I put how to expose with a route inside the paragraph because there is a command for applying the route and a following WARNING about security.

**Comment by ppatierno** [comment]
@scholzj that's a good point but we haven't explained that if you run `oc cluster up` then then the Grafana dashboard is accessible using `http://[service address]:3000` we have only mentioned the minishift/minikube case. So should we add that as well ?

**Comment by scholzj** [comment]
@ppatierno Well, the port forward should work on `oc cluster up` as well, or? Even through it might be not needed ;-)

**Comment by ppatierno** [comment]
@scholzj so we should say "If your cluster is running using `minikube`, `minishift` or on your local PC as host ...." right ?

**Comment by scholzj** [comment]
@ppatierno Well, port-forward works everywhere. So IMHO we can remove the caveats about where it is supported, or?

**Comment by ppatierno** [comment]
Closing this one, we can go with the port forward in any case.

**Pull request closed without merging**
