### PR TITLE
Dedupe controller

### PR DESCRIPTION
**Pull request by tombentley**
This initial PR combines gets rid of the ZookeeperClusterOperations, putting the zookeeper cluster management inside the KafkaClusterOperations. A subsequent PR should be able to simplify the ClusterController, because now the create, update and delete methods on the ClusterController are all essentially the same, so can be pushed inside the AbstractClusterOperations

### CODE REVIEW

**Comment by tombentley** [comment]
@ppatierno sorry, this was motivated by f2f conversation between me and @scholzj. The rationale is that there's quite a lot of boilerplate in the cluster controller, duplication between the different kinds of cluster that it manages. It's not unreasonable to take the stance that each ClusterOperations class should be managing a distinct cluster (thus requiring one specifically for ZK), but it also makes sense for the cluster one to manage the zookeeper resources (since those are a dependency of having a kafka cluster). This refactoring means that those methods can be pushed into the AbstractClusterOperations class (in a later refactoring), which will make the CC itself simpler.

**Comment by tombentley** [comment]
This also fixes #210

**Comment by tombentley** [comment]
@ppatierno @scholzj do you want me to continue this refactoring to include the simplifications in the `ClusterController` which this PR enables, or open a separate PR for that?

**Comment by scholzj** [comment]
I would suggest to use separate PR for the further ClusterController changes.

**Pull request merged**
