### PR TITLE
Fixed path to the ZK healthcheck

### PR DESCRIPTION
**Pull request by ppatierno**
Fixed path to the ZK healthcheck (current ZK image comes from Kafka distribution now)

### CODE REVIEW

**Comment by tombentley** [comment]
This was changed by @scholzj in 79b9d266fbf5fab08411f140478d8e5aa6789785 and I haven't rebased the branch to pick up that change. Maybe we should do that because there might be other problems lurking due to those changes.

**Comment by ppatierno** [comment]
@tombentley agree. Can you rebase and close this PR then ?

**Comment by tombentley** [comment]
@ppatierno rebased+pushed, will now squash a few commits too.

**Comment by scholzj** [comment]
@tombentley @ppatierno Sorry guys, I should have mentioned that. But this should be the only change tot he Java code I did as part of that issue.

**Comment by tombentley** [comment]
No worries @scholzj it was easily rebased over.

**Pull request closed without merging**
