### PR TITLE
Cc limits

### LINKED ISSUE #326: Add Memory and CPU requests and limits for the Cluster Controller deployment YAML files
Currently the YAML files for deploying Cluster Controller do not set and CPU and Memory limits / requests. We should probably set some reasonable defaults.

### PR DESCRIPTION
**Pull request by tombentley**
### Type of change

- Enhancement / new feature

### Description

Fixes #326 and #327 by adding resource limits and requests to the CC and TC YAML resources. The numbers used here were determined by experiment, in both cases two simultaneous reconciliations were observed with stable heap and CPU usage. When significantly lower numbers were use errors were observed.

### Checklist

- [ ] Write tests
- [x] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging

### CODE REVIEW

**Comment by tombentley** [comment]
@ppatierno we already support options to configure those in the `topic-controller-config`. We could, I suppose, set some defaults. But then how would the user configure the topic controller to run without any limits/requests? Maybe that could be done with an empty `resources` object, but I think that's pretty counter-intuitive: For statefulsets and deploymens not specifying any `resources` means you get whatever the cluster is prepared to give you, not some hard coded default. It would be odd if we did differently.

**Comment by tombentley** [comment]
> How many clusters can it take with these resources?

I established those numbers with two clusters.

 > How many topics can TC handle?

I established those numbers with two topics. 

> * Do we want to give it some higher CPU limit?

My observations using visualvm were that CPU usage never exceeded about 15% and that was very transitory. But it's unclear whether that's 15% of the CPU available in the container, 15% of one host core or 15% of the total host CPU available. In any case I tried smaller numbers and it didn't work. It's worth noting that the ST are running slightly slower with these resources than without.

> * Do we want to write something about this into documentation?

The numbers we have here are basically a minimum. They won't be enough for a large installation. But these are *examples* and we would expect users to tailor them to their needs. I can add some words to that effect if you like.

**Comment by scholzj** [comment]
> My observations using visualvm were that CPU usage never exceeded about 15% and that was very transitory. But it's unclear whether that's 15% of the CPU available in the container, 15% of one host core or 15% of the total host CPU available. In any case I tried smaller numbers and it didn't work. It's worth noting that the ST are running slightly slower with these resources than without.

So one of the ideas is to increase the CPU limit as I suggested (i.e. making the CPU burstable - e.g. 200m request and 1000m limit). CPU bustability is easy and Kubernetes should be able to handle it quite well. And it migth speed up the ST again.

> The numbers we have here are basically a minimum. They won't be enough for a large installation. But these are examples and we would expect users to tailor them to their needs. I can add some words to that effect if you like.

The examples are examples, but we are also shipping them pretty much as installation files. So maybe we should be more generous there.

Also, if you think these numbers are _basically a minimum_, we should really list this in the docu.

**Comment by tombentley** [comment]
@scholzj better?

**Pull request merged**
